workflows:
  ios-test:
    name: iOS Test Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build app
        script: |
          xcodebuild build -workspace vadvusd.xcodeproj\project.xcworkspace -scheme vadvusd